<?php echo $this->render("game/ranking/index"); ?>

<table class="ntable">
	<colgroup>
		<col width="30"/>
		<col width="180"/>
		<col width="70"/>
		<col width="80"/>
		<col width="82"/>
		<col width="60"/>
	</colgroup>
	<thead><tr>
		<th>#</th>
		<th>{lang}PLAYER{/lang}</th>
		<th></th>
		<th>{lang}ALLIANCE{/lang}</th>
		<th>{lang}POINTS{/lang}</th>
		<th>{lang}POSITION{/lang}</th>
	</tr></thead>
	<tfoot><tr>
		<td colspan="6">
			<p class="legend"><cite><span>i</span> = {lang}LOWER_INACTIVE{/lang}</cite><cite><span>I</span> = {lang}UPPER_INACTIVE{/lang}</cite><cite><span class="banned">b</span> = {lang}BANNED{/lang}</cite><cite><span class="vacation-mode">v</span> = {lang}VACATION_MODE{/lang}</cite></p>
			<p class="legend"><cite><span class="ownPosition">{lang=ONESELF}</span></cite><cite><span class="alliance">{lang=ALLIANCE}</span></cite><cite><span class="friend">{lang=FRIEND}</span></cite><?php $count = count($this->getLoop("relationTypes")); foreach($this->getLoop("relationTypes") as $key => $row): ?> <cite><span class="{loop=css}">{loop=name}</span></cite> <?php endforeach; ?></p>
		</td>
	</tr></tfoot>
	<tbody><?php $count = count($this->getLoop("ranking")); foreach($this->getLoop("ranking") as $key => $row): ?> <tr>
		<td>{loop}rank{/loop}</td>
		<td>{loop}username{/loop}<?php if($row["user_status"] != ""): ?> ({loop}user_status{/loop})<?php endif; ?></td>
		<td class="center"><?php if($row["userid"] != Core::getUser()->get("userid")): ?>{perm[CAN_MODERATE_USER]}{loop}moderator{/loop} {/perm}{loop}message{/loop} {loop}buddyrequest{/loop}<?php endif; ?></td>
		<td>{loop}alliance{/loop}</td>
		<td>{loop}points{/loop}</td>
		<td>{loop}position{/loop}</td>
	</tr> <?php endforeach; ?></tbody>
</table>