<h1>{lang}Template_Editor{/lang}</h1>
<div class="draggable">
	<form method="post">
		<table class="ntable" cellpadding="4" cellspacing="0">
			<thead>
				<tr>
					<th>{lang}Template_Packages{/lang}</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<strong>{lang}Application_Templates{/lang}</strong><br />
						<?php $count = count($this->getLoop("app")); foreach($this->getLoop("app") as $key => $row): ?> 
						{loop}package{/loop}<br />
						 <?php endforeach; ?><br />
						<strong>{lang}AI_Templates{/lang}</strong><br />
						<?php $count = count($this->getLoop("ai")); foreach($this->getLoop("ai") as $key => $row): ?> 
						{loop}package{/loop}<br />
						 <?php endforeach; ?>
					</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>