<!Doctype html>
<html>
<head>
	<title>{@page}{config=TITLE_GLUE}{@pageTitle}</title>
	<meta charset="{@charset}"/>
	<meta name="robots" content="index,follow"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="{const}BASE_URL{/const}favicon.ico" type="image/x-icon"/>
	<?php if($cssFiles = $this->get("_CSS_FILES")) echo HtmlInclude::getInclude($cssFiles, "css") ?>
	<?php if($jsFiles = $this->get("_JS_FILES")) echo HtmlInclude::getInclude($jsFiles, "js") ?>
</head>
<!--
	The source code of the browsergame engine is copyright protected by Sebastian Noll.
	This copyright notice must retain untouched.
	Website: http://bengine.de/
-->
<body>
<script type="text/javascript">
	//<![CDATA[
	// Define vars
	var userInvalid = '{@userCheck}';
	var emailInvalid = '{lang}EMAIL_CHECK{/lang}';
	var passwordInvalid = '{@passwordCheck}';
	var valid = 'OK';
	var min_user_chars = {config}MIN_USER_CHARS{/config};
	var max_user_cars = {config}MAX_USER_CHARS{/config};
	var min_password_chars = {config}MIN_PASSWORD_LENGTH{/config};
	var max_password_chars = {config}MAX_PASSWORD_LENGTH{/config};
	//]]>
</script>
{hook}FrontHtmlBegin{/hook}
<div class="container">
	<div class="row">
		<div class="col-lg-4 col-md-4">
			<?php if($this->get("langCount", false) > 1): ?>
			<div class="well" id="language">
				<strong>{lang=OTHER_LANGUAGES}</strong><br/>
				<?php $count = count($this->getLoop("languages")); foreach($this->getLoop("languages") as $key => $row): ?>
					<a href="{const=BASE_URL}{loop=langcode}{@selfUrl}"><img src="{const=BASE_URL}img/{loop=langcode}.gif" alt="{loop=title}" title="{loop=title}"/></a></li>
				<?php endforeach; ?>
			</div>
			<?php endif; ?>
			<div class="well">
				<ul class="nav nav-list">
					<li class="nav-header">
						{lang=NAVIGATION}
					</li>
					<li>
						<?php echo Link::get(LANG, "Start") ?>
					</li>
					<?php $count = count($this->getLoop("headerMenu")); foreach($this->getLoop("headerMenu") as $key => $row): ?><li>{loop}link{/loop}</li><?php endforeach; ?>
				</ul>
			</div>
			<div class="well">
				<div class="text-center">
					<a href="#register" class="btn btn-primary btn-large" role="button" data-toggle="modal" data-backdrop="static">{lang=REGISTER_NOW}</a>
				</div>
				<ul class="features">
					<li>{lang=BULLET_1}</li>
					<li>{lang=BULLET_2}</li>
					<li>{lang=BULLET_3}</li>
				</ul>
			</div>
			<div class="well">
				<div class="fb-like" data-href="{const=BASE_URL}" data-send="false" data-layout="button_count" data-width="200" data-show-faces="true"></div>
			</div>
		</div>
		<div class="col-lg-8 col-md-8">
			<div class="well">
				<?php if($this->get("showDefaultContent", false)): ?>
					<h1>{lang}WELCOME{/lang}</h1>
					<p>{lang}GAME_DESCRIPTION{/lang}</p>
				<?php else: ?>
					<?php echo $this->render($template); ?>
				<?php endif; ?>
			</div>
			<div class="well">
				<form action="{const=BASE_URL.LANG}" class="form-horizontal" method="post" id="signin-form">
					<h2>{lang=SIGN_IN}</h2>
					<div class="form-group">
						<label class="col-sm-2 control-label" for="universe">{lang}UNIVERSE{/lang}</label>
						<div class="col-sm-10">
							<select name="universe" id="universe" tabindex="3" class="form-control">
								{@uniSelection}
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label" for="username">{lang}USERNAME{/lang}</label>
						<div class="col-sm-10">
							<input type="text" name="username" id="username" tabindex="1" class="form-control" maxlength="{config=MAX_USER_CHARS}" placeholder="{lang}USERNAME{/lang}" autofocus>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label" for="password">{lang}PASSWORD{/lang}</label>
						<div class="col-sm-10">
							<input type="password" name="password" id="password" tabindex="2" class="form-control" maxlength="{config=MAX_PASSWORD_LENGTH}" placeholder="{lang}PASSWORD{/lang}">
							<span class="help-block">
								<?php echo Link::get(LANG."password", Core::getLanguage()->get("FORGOTTEN")); ?>
							</span>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-10 col-sm-offset-2">
							<button class="btn btn-large btn-success" type="submit" tabindex="4">{lang=SIGN_IN_BUTTON}</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12 text-center">
			Powered by <a href="http://bengine.de">Bengine.de</a>
			<br/>
			Copyright &copy; 2013
		</div>
	</div>
	<div class="modal fade" id="register" role="dialog" aria-hidden="true" aria-labelledby="registerLabel">
		<div class="modal-dialog">
			<form class="modal-content form-horizontal" id="register-form" action="{const=BASE_URL.LANG}">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title" id="registerLabel">{lang=SIGN_UP}</h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label class="control-label col-sm-3" for="registerUsername">{lang=USERNAME}</label>
						<div class="col-sm-7">
							<input type="text" name="username" id="registerUsername" class="form-control" placeholder="{lang=USERNAME}">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-3" for="registerEmail">{lang=EMAIL}</label>
						<div class="col-sm-7">
							<input type="email" name="email" id="registerEmail" class="form-control" placeholder="email@bengine.net">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-3" for="registerPassword">{lang=PASSWORD}</label>
						<div class="col-sm-7">
							<input type="password" name="password" id="registerPassword" class="form-control" placeholder="{lang=PASSWORD}">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-3" for="registerUniverse">{lang=UNIVERSE}</label>
						<div class="col-sm-7">
							<select name="universe" id="registerUniverse" class="form-control">
								{@uniSelection}
							</select>
						</div>
					</div>
					<div id="register-live-check" class="alert"></div>
					<div id="Ajax_Out"><img src="{const=BASE_URL}img/comm-throbber.gif" alt="" width="16" height="16"/></div>
				</div>
				<div class="modal-footer">
					<button class="btn" type="button" data-dismiss="modal" aria-hidden="true">{lang=CANCEL}</button>
					<button class="btn btn-primary" type="submit">{lang=SIGN_UP}</button>
				</div>
			</form>
		</div>
	</div>
	<?php if($this->get("errorMsg", false) != ""): ?>
		<div class="modal fade" id="statusDialog" role="dialog" aria-hidden="true" aria-labelledby="statusDialogLabel">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h4 class="modal-title" id="statusDialogLabel">{lang=ERROR}</h4>
					</div>
					<div class="modal-body">
						{@errorMsg}
					</div>
					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">{lang=OK}</button>
					</div>
				</div>
			</div>
		</div>
	<?php endif ?>
</div>
<div id="fb-root"></div>
<script>(function(d, s, id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="//connect.facebook.net/de_DE/all.js#xfbml=1";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));</script>
{hook}FrontHtmlEnd{/hook}
</body>
</html>