<form method="post" action="{@formaction}">
<input type="hidden" name="moon" value="{request[get]}moon{/request}"/>
<table class="ntable">
	<tr>
		<th colspan="2">{lang}ROCKET_ATTACK{/lang}: {@target}</th>
	</tr>
	<tr>
		<td>{lang=FLY_DURATION}</td>
		<td>{@flightDuration}</td>
	</tr>
	<tr>
		<td>{lang}QUANTITY{/lang} ({lang}MAX{/lang} {@rockets})</td>
		<td><input type="text" name="quantity" value="0"/></td>
	</tr>
	<tr>
		<td>{lang}PRIMARY_TARGET{/lang}</td>
		<td><select name="target"><option>{lang}ALL{/lang}</option><?php $count = count($this->getLoop("destionations")); foreach($this->getLoop("destionations") as $key => $row): ?> <option value="{loop}unitid{/loop}">{loop}name{/loop}</option> <?php endforeach; ?></select></td>
	</tr>
	<tr>
		<td colspan="2" class="center"><input type="submit" name="start" value="{lang}ATTACK{/lang}" class="button" /></td>
	</tr>
</table>
</form>