<?php echo $this->render("game/search/index"); ?>
<table class="ntable">
	<tr>
		<th>{lang}TAG{/lang}</th>
		<th>{lang}ALLIANCE{/lang}</th>
		<th>{lang}MEMBERS{/lang}</th>
		<th>{lang}POINTS{/lang}</th>
	</tr>
	<?php $count = count($this->getLoop("result")); foreach($this->getLoop("result") as $key => $row): ?> <tr>
		<td>{loop}tag{/loop}</td>
		<td>{loop}name{/loop}</td>
		<td>{loop}members{/loop}</td>
		<td>{loop}points{/loop}</td>
	</tr> <?php endforeach; ?>
	<?php if(count($this->loopStack["result"]) == 0): ?><tr>
		<td colspan="4" class="center">{lang}NO_MATCHES_FOUND{/lang}</td>
	</tr><?php endif; ?>
</table>