<form method="post" action="{@formaction}" class="form-sec">
<table class="ntable">
	<thead><tr>
		<th colspan="2">{lang}STAR_GATE_JUMP{/lang}</th>
	</tr></thead>
	<?php if(count($this->loopStack["moons"]) > 0): ?>
	<tfoot>
		<tr>
			<td colspan="2">
				<input type="hidden" name="execjump" value="1"/>
				<input type="submit" value="{lang}EXECUTE_JUMP{/lang}" class="button" />
			</td>
		</tr>
	</tfoot><?php endif; ?>
	<tbody><tr>
		<td><label for="moonid">{lang}SELECT_TARGET_MOON{/lang}</label></td>
		<td>
			<select name="moonid" id="moonid"><?php $count = count($this->getLoop("moons")); foreach($this->getLoop("moons") as $key => $row): ?> <option value="{loop}planetid{/loop}">{loop}planetname{/loop} [{loop}galaxy{/loop}:{loop}system{/loop}:{loop}position{/loop}]</option> <?php endforeach; ?></select>
		</td>
	</tr></tbody>
</table>
</form>