<form method="post" action="{@formaction}">
<table class="ntable">
	<thead><tr>
		<th colspan="{@colspan}">{lang}MEMBER_LIST{/lang} ({lang}TOTAL_MEMBERS{/lang}: {@totalmembers} / {@totalpoints})</th>
	</tr>
	<tr>
		<td>{lang}USERNAME{/lang}</td>
		<td></td>
		<td>{lang}RANK{/lang}</td>
		<td>{lang}POINTS{/lang}</td>
		<td>{lang}POSITION{/lang}</td>
		<td>{lang}JOIN_DATE{/lang}</td>
		<?php if($this->get("can_see_onlie_state")): ?><td></td><?php endif; ?>
		<?php if($this->get("can_ban_member")): ?><td></td><?php endif; ?>
	</tr></thead>
	<?php if($this->get("can_manage")): ?><tfoot><tr>
		<td colspan="{@colspan}" class="center"><input type="submit" name="changeMembers" value="{lang}PROCEED{/lang}" class="button" /></td>
	</tr></tfoot><?php endif; ?>
	<tbody><?php $count = count($this->getLoop("members")); foreach($this->getLoop("members") as $key => $row): ?> <tr>
		<td>{loop}username{/loop}</td>
		<td>{loop}message{/loop}</td>
		<td><?php if($this->get("founder") == $row["userid"] || !$this->get("can_manage")): ?>{loop}rank{/loop}<?php else: ?><select name="rank_{loop}userid{/loop}"><option value="0">{lang}NEWBIE{/lang}</option>{loop}rankselection{/loop}</select><?php endif; ?></td>
		<td>{loop}points{/loop}</td>
		<td>{loop}position{/loop}</td>
		<td>{loop}joindate{/loop}</td>
		<?php if($this->get("can_see_onlie_state")): ?><td>{loop}online{/loop}</td><?php endif; ?>
		<?php if($this->get("can_ban_member")): ?><td><?php if($this->get("founder") != $row["userid"]): ?><input type="image" src="{@themePath}img/error2.gif" name="kick_{loop}userid{/loop}" title="{lang}REMOVE{/lang}" alt="{lang}REMOVE{/lang}" /><?php endif; ?></td><?php endif; ?>
	</tr> <?php endforeach; ?></tbody>
</table>
</form>