<table class="ntable">
	<thead>
		<tr>
			<th colspan="2">
				{lang}STATISTICS_HEADER{/lang}
			</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th colspan="2">
				{lang}STATISTICS_GALAXY{/lang}
			</th>
		</tr>
		<tr>
			<td>
				{lang}ALL_PLAYERS{/lang}:
			</td>
			<td>
				{@totalPlayers}
			</td>
		</tr>
		<tr>
			<td>
				{lang}ONLINE_NOW{/lang}:
			</td>
			<td>
				{@totalOnline}
			</td>
		</tr>
		<tr>
			<td>
				{lang}ALL_PLANETS{/lang}:
			</td>
			<td>
				{@totalPlanets}
			</td>
		</tr>
		<tr>
			<td>
				{lang}ALL_MOONS{/lang}
			</td>
			<td>
				{@totalMoons}
			</td>
		</tr>
		<tr>
			<td>
				{lang}TOTAL_DEBRIS_FIELDS{/lang}:
			</td>
			<td>
				{@totalDebrisFields}
			</td>
		</tr>
		<tr>
			<td>
				{lang}RECENT_ASSAULTS{/lang}:
			</td>
			<td>
				{@totalRecentAssaults}
			</td>
		</tr>
		<tr>
			<th colspan="2">
				{lang}STATISTICS_RESSOURCES{/lang}
			</th>
		</tr>
		<tr>
			<td>
				{lang}STATISTICS_METAL{/lang}:
			</td>
			<td>
				{@totalMetal} ({@percentMetal} %)
			</td>
		</tr>
		<tr>
			<td>
				{lang}STATISTICS_SILICON{/lang}:
			</td>
			<td>
				{@totalSilicon} ({@percentSilicon} %)
			</td>
		</tr>
		<tr>
			<td>
				{lang}STATISTICS_HYDROGEN{/lang}:
			</td>
			<td>
				{@totalHydrogen} ({@percentHydrogen} %)
			</td>
		</tr>

		<?php $translator = Core::getLang() ?>
		<?php $ships = $this->getLoop("ships") ?>
		<?php $fleet = $ships[Bengine_Game_Controller_Shipyard::FLEET_CONSTRUCTION_TYPE] ?>
		<tr>
			<th colspan="2">
				{lang}STATISTICS_SHIPS{/lang}: {lang=FLEET}
			</th>
		</tr>
		<?php foreach($fleet as $name => $total): ?>
		<?php if($total): ?>
		<tr>
			<td><?php echo $translator->get($name) ?></td>
			<td><?php echo fNumber($total) ?></td>
		</tr>
		<?php endif ?>
		<?php endforeach ?>
		<tr>
			<th colspan="2">
				{lang}STATISTICS_SHIPS{/lang}: {lang=DEFENSE}
			</th>
		</tr>
		<?php $defense = $ships[Bengine_Game_Controller_Shipyard::DEFENSE_CONSTRUCTION_TYPE] ?>
		<?php foreach($defense as $name => $total): ?>
		<?php if($total): ?>
		<tr>
			<td><?php echo $translator->get($name) ?></td>
			<td><?php echo fNumber($total) ?></td>
		</tr>
		<?php endif ?>
		<?php endforeach ?>
	</tbody>
</table>