<table class="ntable">
	<tr>
		<th>{lang}CONSTRUCTION{/lang}</th>
		<th>{lang}REQUIREMENTS{/lang}</th>
	</tr>
	{foreach[construction]}<tr>
		<td>{loop}name{/loop}</td>
		<td>{loop}requirements{/loop}</td>
	</tr>{/foreach}
	<tr>
		<th>{lang}MENU_RESEARCH{/lang}</th>
		<th>{lang}REQUIREMENTS{/lang}</th>
	</tr>
	{foreach[research]}<tr>
		<td>{loop}name{/loop}</td>
		<td>{loop}requirements{/loop}</td>
	</tr>{/foreach}
	<tr>
		<th>{lang}SHIPYARD{/lang}</th>
		<th>{lang}REQUIREMENTS{/lang}</th>
	</tr>
	{foreach[shipyard]}<tr>
		<td>{loop}name{/loop}</td>
		<td>{loop}requirements{/loop}</td>
	</tr>{/foreach}
	<tr>
		<th>{lang}DEFENSE{/lang}</th>
		<th>{lang}REQUIREMENTS{/lang}</th>
	</tr>
	{foreach[defense]}<tr>
		<td>{loop}name{/loop}</td>
		<td>{loop}requirements{/loop}</td>
	</tr>{/foreach}
	<tr>
		<th>{lang}MOON_BUILDING{/lang}</th>
		<th>{lang}REQUIREMENTS{/lang}</th>
	</tr>
	{foreach[moon]}<tr>
		<td>{loop}name{/loop}</td>
		<td>{loop}requirements{/loop}</td>
	</tr>{/foreach}
</table>